build:bionic:
    image: ubuntu:18.04
    stage: build
    only:
        - pushes
    script:
        - ./ci/gitlab-ci/ubuntu/18.04/build.sh
    artifacts:
        paths:
            - build/*.deb
        expire_in: 1h

build:focal:
    image: ubuntu:20.04
    stage: build
    only:
        - pushes
    script:
        - ./ci/gitlab-ci/ubuntu/20.04/build.sh

test:bionic:
    image: ubuntu:18.04
    stage: test
    dependencies:
        - build:bionic
    script:
        - ls build/
        - dpkg -i build/*.deb
        - apt-get -f install
        - dpkg -i build/*.deb

pages:
    image: gcc
    stage: deploy
    only:
        - pushes
    script:
        - apt-get update && apt-get install -y cmake doxygen graphviz
        - mkdir build
        - cd build
        - cmake .. -DDOC_ONLY=true
        - make doc
        - mv html ..
        - cd ..
        - mv html public
    artifacts:
        paths:
            - public

