build:bionic:
    image: ubuntu:18.04
    stage: build
    only:
        - pushes
    script:
        - ./ci/gitlab-ci/ubuntu/18.04/build.sh

build:focal:
    image: ubuntu:20.04
    stage: build
    only:
        - pushes
    script:
        - ./ci/gitlab-ci/ubuntu/20.04/build.sh

pages:
    image: gcc
    stage: deploy
    only:
        - pushes
    script:
        - apt-get update && apt-get install -y cmake doxygen graphviz
        - mkdir build
        - cd build
        - cmake .. -DDOC_ONLY=true
        - make doc
        - mv html ..
        - cd ..
        - mv html public
    artifacts:
        paths:
            - public

